num1 = int(input("Enter first number : "))
num2 = int(input("Enter second number : "))

print("Addition = ",num1+num2)
print("Substraction = ",num1-num2)
print("Multiplication = ",num1*num2)
print("Modulus = ",num1%num2)
print("Division = ",num1/num2)
print("Floor Division = ",num1//num2)
print("Exponantiation = ",num1**num2)